###
GET http://localhost:5192

###
GET http://localhost:5192/games

###
GET http://localhost:5192/games/14

###
POST http://localhost:5192/games
Content-Type: application/json

{
    "name": "Fast and Furious",
    "genreId": 3,
    "price": 100,
    "releaseDate": "2013-09-17"
}

###
PUT http://localhost:5192/games/14
Content-Type: application/json

{
    "name": "GTA V",
    "genreId": 3,
    "price": 100,
    "releaseDate": "2013-09-17"
}

###
DELETE http://localhost:5192/games/11

###
PATCH http://localhost:5192/games/14
Content-Type: application/json

{
    "name": "GTA VI"
}